apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: klaversjassen-ai
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: klaversjassen-ai
  project: default
  source:
    repoURL: https://github.com/bhuism/home-ops.git
    path: charts/klaversjassen-ai
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
